# Generated by Django 5.1.6 on 2025-03-28 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toc', '0005_rename_service_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('interrupteurs', 'Interrupteurs'), ('sanitaires', 'Produits Sanitaires'), ('pomelles', 'Pomelles'), ('cabines_douche', 'Cabines de Douche')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toc.categorie'),
        ),
    ]
