# Generated by Django 5.1.6 on 2025-03-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toc', '0007_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='nom',
            new_name='name',
        ),
    ]
