# Generated by Django 5.1.6 on 2025-03-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toc', '0008_rename_nom_categorie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_product.png', upload_to='products/'),
        ),
    ]
